---
title: "2.1.3 Summarize data (Q level)"
output: html_document
---

# Run before summarizing data
```{r}
#install packages
# install.packages("reshape2")
# install.packages("ggplot2")
# install.packages("dplyr")
# install.packages("lubridate")
# install.packages("tcltk")
# install.packages("rJava")

#load packages
library(reshape2)
library(ggplot2)
library(dplyr)
library(lubridate)
library(tcltk)
library(rJava)



```

# Number of factories per cycle
```{r}


```

# b) Noncompliance at the Q level
## i. By latest assessment in specified dates
```{r}
#store the function
get_compliance_question_by_time_period <- function(df,m1,m2,y1,y2){
    temp_df <- df
    temp_df <- temp_df[!grepl("(Obsolete)",temp_df$Factory.Assessed.Name),]
    temp_df$date_final <- as.Date(temp_df$Assesment.Start.Date, "%d/%m/%Y")
    temp_df$Year <- as.numeric(format(temp_df$date_final, "%Y"))
    temp_df$Month <- as.numeric(format(temp_df$date_final, "%m"))
    if(y1 == y2){
      temp_df <- temp_df[(temp_df$Year == y1 & temp_df$Month >= m1 & temp_df$Month <= m2),]
    }else{
      temp_df <- temp_df[(temp_df$Year == y1 & temp_df$Month >= m1) |
                                 (temp_df$Year == y2 & temp_df$Month <= m2)|
                         (temp_df$Year > y1 & temp_df$Year < y2),]
    }
    
    latest_date_for_each_factory <- temp_df %>%
      group_by(Factory.Assessed.Name)%>%
      summarise(Quest.ID = max(Quest.ID))
  
    # latest_date_for_each_factory$latest_assessment_date <- 1

    temp_df <- inner_join(temp_df,latest_date_for_each_factory,
                           by = c('Factory.Assessed.Name','Quest.ID'))

    temp_df <- temp_df[temp_df$Question.type != "FGW",]
    
    

    temp_df$Finding <- as.integer(temp_df$Finding)
    temp_df$public_reporting <- ifelse(grepl("Public Disclosure",temp_df$Tags),1,0)
    
    compliance_question_count <- temp_df%>%
      group_by(Q.Label,Question.ID,CP,Cluster,public_reporting,Tags)%>%
      summarise(number_nc_factories = sum(Finding), total_factories = n_distinct(Quest.ID))
    return (compliance_question_count)
}

#use the function (example)
#here, we measure noncompliance rates between January 2017 and February 2018, for all the latest assessments of each factory in the specified timeframe. The set of dates can be replaced following the order: "m1, m2, y1, y2," where m1 and y1 are the start date (month and year), and m2 and y2 the end date of the timeframe taken into consideration
noncompliance_rate_example <-get_compliance_question_by_time_period(data,1,12,2010,2022)

```

## ii. For a chosen cycle in specified dates
```{r}
#store the function
get_compliance_question_by_time_and_cycle <- function(df,m1,m2,y1,y2,cycle){
    temp_df <- df
    temp_df <- temp_df[!grepl("(Obsolete)",temp_df$Factory.Assessed.Name),]
    temp_df <- temp_df[!duplicated(temp_df),]
    temp_df$date_final <- as.Date(temp_df$Assesment.Start.Date, "%d/%m/%Y")
    temp_df$Year <- as.numeric(format(temp_df$date_final, "%Y"))
    temp_df$Month <- as.numeric(format(temp_df$date_final, "%m"))
    if(y1 == y2){
      temp_df <- temp_df[(temp_df$Year == y1 & temp_df$Month >= m1 & temp_df$Month <= m2),]
    }else{
      temp_df <- temp_df[(temp_df$Year == y1 & temp_df$Month >= m1) |
                                 (temp_df$Year == y2 & temp_df$Month <= m2)|
                         (temp_df$Year > y1 & temp_df$Year < y2),]
    }
    
    temp_df <- temp_df[temp_df$Cycle == cycle,]

    temp_df <- temp_df[temp_df$Question.type != "FGW",]

    temp_df$Finding <- as.integer(temp_df$Finding)
    temp_df$public_reporting <- ifelse(grepl("Public Disclosure",temp_df$Tags),1,0)
    
    compliance_question_count <- temp_df%>%
      group_by(Q.Label,CP,Cluster,public_reporting,Tags)%>%
      summarise(number_nc_factories = sum(Finding), total_factories = n_distinct(Quest.ID))
    return (compliance_question_count)
}

#use the function (example)
#we calculate noncompliance rates between May 2015 and July 2017 for all first assessment cycles. The criteria can be replaced with a different timeframe and cycle number following the order: "m1, m2, y1, y2, cycle" where m1 and y1 is the start date (month and year), and m2 and y2 the end date of the specified timeframe, and cycle is the cycle number that we wish to take into consideration 
noncompliance_question_example_cycle <-get_compliance_question_by_time_and_cycle(data,1,12,2010,2022, 1)

save(list=ls(),file="/Users/malik/Dropbox (GALILEO)/Master Thesis/RManual-master/Data Sets/BetterWorksClusteredNonCPQLevel.RData")
```
