---
title: "3.1 Create a Balanced Panel"
output: html_document
---

# Run before preparing data
```{r}
#install packages
# install.packages("reshape2")
# install.packages("ggplot2")
# install.packages("dplyr")
# install.packages("lubridate")
# install.packages("tcltk")
# install.packages("rJava")

#load packages
library(reshape2)
library(ggplot2)
library(dplyr)
library(lubridate)
library(tcltk)
library(rJava)
```

# Open data
```{r}
assessment_example <- data
```

# Count factories by cycle
```{r}
table_of_cycle_countries <- assessment_example%>%
  group_by(Country,Cycle)%>%
  summarise(number_of_factories = n_distinct(Factory.Assessed.ID))
```

# Visually inspect sample size 
```{r}
table_to_inspect_sample_size <- dcast(table_of_cycle_countries,Country ~ Cycle, value.var="number_of_factories")
View(table_to_inspect_sample_size)
```

# Summarize noncompliance for a balanced panel of factories
```{r}
#store the function
get_nc_rates_by_cycle_for_all_cycles_less_than_a_given_cycle <- function(df,cyc){
  temp_df <- df
  temp_df <- temp_df[!grepl("(Obsolete)",temp_df$Factory.Assessed.Name),]
  temp_df <- temp_df[!duplicated(temp_df),]
  temp_df$date_final <- as.Date(temp_df$Assesment.Start.Date, "%d/%m/%Y")
  temp_df$Cycle <- as.numeric(temp_df$Cycle)

  factory_ids_we_want <- df%>%
    group_by(Factory.Assessed.ID)%>%
    summarise(largest_cycle = max(Cycle))%>%
    filter(largest_cycle >= cyc)
  
  temp_df <- temp_df%>%
    filter(Factory.Assessed.ID %in% factory_ids_we_want$Factory.Assessed.ID 
           & Cycle <= cyc & Question.type != "FGW")

  temp_df$Finding <- as.integer(temp_df$Finding)


    # Making some modifications to consolidate the hazardous forms and the OSH cluster
    
  haz_and_worst_forms <- c("Hazardous Work","Hazardous Work and other Worst Forms","Unconditional Worst Forms")

  temp_df$CP<- ifelse(temp_df$CP %in% haz_and_worst_forms,"Hazardous Work and other Worst forms",temp_df$CP)
  temp_df$Cluster <- ifelse(temp_df$Cluster == "Systems", "Occupational Safety and Health", temp_df$Cluster)  

  compliance_calc <- temp_df%>%
    group_by(Country,Cluster, Quest.ID,CP,Cycle)%>%
    summarise(findings = sum(Finding))
    
  compliance_calc$non_compliant <-ifelse(compliance_calc$findings >0,1,0)

  compliance_df <- compliance_calc%>%
    group_by(Country,CP,Cluster,Cycle)%>%
    summarise(total_factories=n(),number_non_compliant= sum(non_compliant), percent_non_cp = sum(non_compliant)/n())

    return (compliance_df)  
}

#use the function (example)
nc_cp_trends <- get_nc_rates_by_cycle_for_all_cycles_less_than_a_given_cycle(assessment_example,6)

aggr <- aggregate(percent_non_cp ~ Country + Cycle,data=nc_cp_trends,mean)
View(aggr)
ggplot(aggr,aes(x=Cycle,y=percent_non_cp,color=Country))+geom_line()

aggr2<- aggregate(percent_non_cp ~ Cluster + Cycle,data=nc_cp_trends,mean)

ggplot(aggr2,aes(x=Cycle,y=percent_non_cp,color=Cluster))+geom_line()



```