---
title: "Setting up Cycle-to-cycle Trends for Indonesia and other Countries"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(dplyr)
library(readxl)
library(reshape2)

```

###output choices
```{r}

load("/Users/malik/Dropbox (GALILEO)/Master Thesis/RManual-master/cycle-trend-panel-creation-main/All Better Work Assessments through 8 February 2022.Rda")
# all_bw_assessments_through_8_feb_2022
##choose country(s)
countries <- unique(all_bw_assessments_through_8_feb_2022$Country)
###choose the number of Cycles for which you want a panel
###Note: choose 3 or more. Less than 3 cycles is not really a visible trend.
###its preferable to choose even more (5 or more cycles) since the 
###drop in NC rates ususally occurr after the first 3 cycles and cycles 4 and 5 are
###when we generally see plateaus
cycle_vector <- c(3:10)
####paste together names for output string names


countries_in_panel <- ''
for(country in countries){
  countries_in_panel <- paste(countries_in_panel, country)
  
}

cycles_in_sample <- paste0(min(cycle_vector)," - ",max(cycle_vector))

question_level_panel_string_file_names <- paste0(countries_in_panel,
                                         " Question Level Panel for factories with at least ",
                                         cycles_in_sample,
                                         " Cycles with Better Work.csv")

compliance_point_level_panel_string_file_names <- paste0(countries_in_panel,
                                         " Compliance Point Level Panel for factories with at least ",
                                         cycles_in_sample,
                                         " Cycles with Better Work.csv")


```

###formatting cat_document
```{r}
# Input data includes: cat_document, all better work assessments, and the enterprise report


####got rid of Tags to make things easier for 
cat_document <- read_excel('/Users/malik/Dropbox (GALILEO)/Master Thesis/RManual-master/cycle-trend-panel-creation-main/2022-02-01_All CAT questions with with Global Identifiers and all Tags.xlsx')%>%
  group_by(country_name, cluster_name, compliance_point_name,first_original_question_id,question_id,
           text,finding,question_type,global_question_mapping_id,global_text,global_finding)%>%
  summarise(n=n())%>%
  select(-n)



end_period_2021 <- as.Date("31/12/2021","%d/%m/%Y")
active_factories_used_for_end_of_year_reporting <- read_excel('/Users/malik/Dropbox (GALILEO)/Master Thesis/RManual-master/cycle-trend-panel-creation-main/Enterprise_Report_All_01-02-2022.xlsx', skip = 1)%>%
  rename(Creation..Data = `Creation  Data`)%>%
  rename(Country = Country...11)%>%
  mutate(ID = as.integer(ID))%>%
  filter(Status %in% 'Active')%>%
  filter(as.Date(Creation..Data,"%d/%m/%Y") <= end_period_2021)


all_factories_ever_in_programme <- read_excel('/Users/malik/Dropbox (GALILEO)/Master Thesis/RManual-master/cycle-trend-panel-creation-main/Enterprise_Report_All_01-02-2022.xlsx', skip = 1)%>%
  rename(Creation..Data = `Creation  Data`)%>%
  rename(Country = Country...11)%>%
  mutate(ID = as.integer(ID))%>%
  # filter(Status %in% 'Active')%>%
  filter(as.Date(Creation..Data,"%d/%m/%Y") <= end_period_2021)


```


###Creating the Panel...
```{r}

###write function to get all of the potential balanced panels....

# loop through the number of cycles and aggregate based on the active factories...

####Legacy
generate_cycle_by_cycle_panel_for_all_qlabels <- function(countries = NULL,cycle_vec,df_of_data,active_factories_df,cat_doc){
  
  global_identifiers_for_all_question_ids <- cat_doc%>%
    group_by(question_id,global_question_mapping_id)%>%
    summarise(n=n())%>%
    select(question_id,global_question_mapping_id)
  
  largest_question_id_for_global_identifier <- cat_doc%>%
    group_by(global_question_mapping_id,country_name)%>%
    summarise(largest_question_id = max(question_id))
  
    if(is.null(countries)){
      temp_df <- df_of_data
    }else{
      temp_df <- df_of_data%>%
        filter(Country %in% countries)
    }
    
    temp_df <- temp_df[!grepl("(Obsolete)",temp_df$Factory.Assessed.Name),]%>%
      inner_join(global_identifiers_for_all_question_ids, by = c('Question.ID'='question_id'))

    ###getting the largest question_id for the temp_df for any given global identifier
    ###this is just to use for labeling purposess
    
    #for all unique global_questions...we make sure that there is
    ##question_id that will represent the latest Q.Label to use 
    largest_q_id_for_each_global_in_sample <- temp_df%>%
      group_by(global_question_mapping_id,Country)%>%
      summarise(sample_largest_question_id = max(Question.ID))

    temp_df <- temp_df%>%
      inner_join(largest_q_id_for_each_global_in_sample, by = c('global_question_mapping_id','Country'))%>%
      inner_join(cat_doc[,c('text','question_id')], 
                 by = c('sample_largest_question_id' = 'question_id'))%>%
      rename(latest_question_label = text)

    temp_df <- temp_df[temp_df$Question.type != "FGW",]
  
    temp_df$converted_finding <- as.integer(temp_df$Finding)
    # temp_df$public_reporting <- ifelse(grepl("Public Disclosure",temp_df$Tags),1,0)
  
    
  ####the panel construction portion...
    
  latest_cycle_for_active_factories <- temp_df%>%
    group_by(Factory.Assessed.ID)%>%
    summarise(Cycle = max(Cycle))%>%
    filter(Factory.Assessed.ID %in% active_factories_df$ID)
  
  output_df <- data.frame(Country = character(),
                          Q.Label = character(),
                          sample_largest_question_id = numeric(),
                          # public_reporting = integer(),
                          CP = character(),
                          Cluster = character(),
                          Cycle =integer(),
                          total_ncs = integer(),
                          total_factories = integer(),
                          nc_rate = numeric())
  
  for(cyc in cycle_vec){
    
    #these are factories that have has at least as many cycles as the cycle passed in the loop
    factories_to_use <- temp_df%>%
      filter(Factory.Assessed.ID %in% latest_cycle_for_active_factories$Factory.Assessed.ID)%>%
      filter(Cycle >= cyc)%>%
      group_by(Factory.Assessed.ID)%>%
      summarise(n=n())
    ####need to merge in the information....
    temp_panel_data <- temp_df%>%
      filter(Factory.Assessed.ID %in% factories_to_use$Factory.Assessed.ID)%>%
      filter(Cycle <= cyc)
    
    panel_df <- temp_panel_data%>%
      group_by(Country,Q.Label,sample_largest_question_id,CP,Cluster,Cycle)%>%
      summarise(total_ncs = sum(converted_finding),
                total_factories = n_distinct(Factory.Assessed.ID),
                nc_rate = sum(converted_finding)/n_distinct(Factory.Assessed.ID))
    
    output_df <- rbind(output_df,panel_df)
    
  }
  
  return(output_df)
  
}
####Legacy


generate_cycle_by_cycle_panel_for_all_qlabels_with_pre_labeling <- function(countries = NULL,cycle_vec,df_of_data,active_factories_df,cat_doc){
  
  global_identifiers_for_all_question_ids <- cat_doc%>%
    group_by(question_id,global_question_mapping_id)%>%
    summarise(n=n())%>%
    select(question_id,global_question_mapping_id)
  
  largest_question_id_for_global_identifier <- cat_doc%>%
    group_by(global_question_mapping_id,country_name)%>%
    summarise(largest_question_id = max(question_id))
  
    if(is.null(countries)){
      temp_df <- df_of_data
    }else{
      temp_df <- df_of_data%>%
        filter(Country %in% countries)
    }
    
    temp_df <- temp_df[!grepl("(Obsolete)",temp_df$Factory.Assessed.Name),]%>%
      inner_join(global_identifiers_for_all_question_ids, by = c('Question.ID'='question_id'))

    ###getting the largest question_id for the temp_df for any given global identifier
    ###this is just to use for labeling purposess
    
    #for all unique global_questions...we make sure that there is
    ##question_id that will represent the latest Q.Label to use 
    largest_q_id_for_each_global_in_sample <- temp_df%>%
      group_by(global_question_mapping_id,Country)%>%
      summarise(sample_largest_question_id = max(Question.ID))

    temp_df <- temp_df%>%
      inner_join(largest_q_id_for_each_global_in_sample, by = c('global_question_mapping_id','Country'))%>%
      inner_join(cat_doc[,c('text','question_id')], 
                 by = c('sample_largest_question_id' = 'question_id'))%>%
      rename(latest_question_label = text)

    temp_df <- temp_df[temp_df$Question.type != "FGW",]
  
    temp_df$converted_finding <- as.integer(temp_df$Finding)
    # temp_df$public_reporting <- ifelse(grepl("Public Disclosure",temp_df$Tags),1,0)
  
    
  ####the panel construction portion...
    
  latest_cycle_for_active_factories <- temp_df%>%
    group_by(Factory.Assessed.ID)%>%
    summarise(Cycle = max(Cycle))%>%
    filter(Factory.Assessed.ID %in% active_factories_df$ID)
  
  output_df <- data.frame(Country = character(),
                          latest_question_label = character(),
                          sample_largest_question_id = numeric(),
                          # public_reporting = integer(),
                          CP = character(),
                          Cluster = character(),
                          Cycle =integer(),
                          total_ncs = integer(),
                          total_factories = integer(),
                          nc_rate = numeric(),
                          min_factories_in_panel = integer(),
                          max_factories_in_panel = integer(),
                          balanced = integer(),
                          unique_panel_name = character(),
                          broad_panel_name = character(),
                          complete = integer(),
                          all_zero = integer())
  
  for(cyc in cycle_vec){
    
    #these are factories that have has at least as many cycles as the cycle passed in the loop
    factories_to_use <- temp_df%>%
      filter(Factory.Assessed.ID %in% latest_cycle_for_active_factories$Factory.Assessed.ID)%>%
      filter(Cycle >= cyc)%>%
      group_by(Factory.Assessed.ID)%>%
      summarise(n=n())
    ####need to merge in the information....
    temp_panel_data <- temp_df%>%
      filter(Factory.Assessed.ID %in% factories_to_use$Factory.Assessed.ID)%>%
      filter(Cycle <= cyc)
    
    ####From this temp panel data: we should:
    #1) take all of the unique sample_largest_question_id
    #2) calculate the NCs
    #3) assign a column with panel max, panel min, 
    #4) define if balanced if panel_max == panel_min
    #5) give a unique identifier based in the data
    #6) rbind to output_df
    
    
    for(temp_question_id in unique(temp_panel_data$sample_largest_question_id)){
      ###subset for all of the temp_panel_data 
      panel_df <- temp_panel_data%>%
        filter(sample_largest_question_id %in% temp_question_id)%>%
        group_by(Country,latest_question_label,sample_largest_question_id,CP,Cluster,Cycle)%>% ###change here to latest_question_label from Q.Label
        summarise(total_ncs = sum(converted_finding),
                  total_factories = n_distinct(Factory.Assessed.ID),
                  nc_rate = sum(converted_finding)/n_distinct(Factory.Assessed.ID))
      
      panel_df$max_factories_in_panel <- max(panel_df$total_factories)
      panel_df$min_factories_in_panel <- min(panel_df$total_factories)
      panel_df$balance  <- ifelse(panel_df$max_factories_in_panel == panel_df$min_factories_in_panel,
                                  1,0)
      panel_df$unique_panel_name <- paste0("Factories with at least ",max(panel_df$Cycle)," cycles for Question ID ", panel_df$sample_largest_question_id, " Balanced = ",panel_df$balance)
      panel_df$broad_panel_name <- paste0("Factories with at least ",max(panel_df$Cycle))
      panel_df$complete <- ifelse(panel_df$max_factories_in_panel == cyc,1,0)

      
      ###check if all zero to allow for elimination:
      
      all_zero <- panel_df%>%
        group_by(unique_panel_name)%>%
        summarise(agg_nc = sum(nc_rate))%>%
        mutate(all_zero = ifelse(agg_nc == 0, 1,0))%>%
        select(unique_panel_name,all_zero)
      
      panel_df <- inner_join(panel_df,all_zero, by = 'unique_panel_name')
      ###ass
    
    output_df <- rbind(output_df,panel_df) 
    }

  }
# 
#    ###check if downward trend
#       
    # balanced_and_complete_panesl <- output_df%>%
    #   filter(balance == 1 & all_zero == 0)
    
    getting_high_low <- output_df%>%
      group_by(unique_panel_name)%>%
      summarise(min_cycle = min(Cycle),
                max_cycle = max(Cycle))%>%
      inner_join(output_df,by = 'unique_panel_name')
    
    wide_view <- dcast(getting_high_low,unique_panel_name + min_cycle + max_cycle ~ Cycle,value.var = 'nc_rate',
                       fun.aggregate = mean)
    
    wide_view$panel_beginning <- NA
    wide_view$panel_end <- NA
    for(row in 1:nrow(wide_view)){
      # wide_view[row,as.character(wide_view$min_cycle[row])]
      wide_view$panel_beginning[row] <- as.numeric(wide_view[row,as.character(wide_view$min_cycle[row])])
      wide_view$panel_end[row] <- as.numeric(wide_view[row,as.character(wide_view$max_cycle[row])])
      # print(wide_view[row,as.character(wide_view$min_cycle[row])])
      # print(as.character(wide_view$min_cycle[row]))
    }
    
    wide_view$downward_trend <- ifelse(wide_view$panel_beginning > wide_view$panel_end,1,0)
    
    final_output_df <- inner_join(output_df,
                                                                wide_view%>%select(unique_panel_name,downward_trend),
                                                                by = 'unique_panel_name')

    return(final_output_df)
  # return(output_df)
}

####Legacy...not used in output
panel_production_for_all_qlabels <- generate_cycle_by_cycle_panel_for_all_qlabels(countries,
                                                                                  cycle_vector,
                                                                  all_bw_assessments_through_8_feb_2022,
                                                                  active_factories_used_for_end_of_year_reporting,
                                                                  cat_document)
#####Legacy...not used in output


####This is used for the actual output
###takes about 6-8 minutes to run
panel_production <- generate_cycle_by_cycle_panel_for_all_qlabels_with_pre_labeling(countries,
                                                                                  cycle_vector,
                                                                  all_bw_assessments_through_8_feb_2022,
                                                                  active_factories_used_for_end_of_year_reporting,
                                                                  cat_document)


broad_panel <- "Factories with at least 6"
cp <-"Leave"

checking_leave_over_6 <- panel_production_second_try%>%
  filter(broad_panel_name %in% broad_panel & CP %in% cp)

#this is for all factories that have ever been part of the programme
##may be useful if looking back retroactively or for COVID
panel_production_all_factories_ever <- generate_cycle_by_cycle_panel_for_all_qlabels_with_pre_labeling(countries,
                                                                                  cycle_vector,
                                                                  all_bw_assessments_through_8_feb_2022,
                                                                  all_factories_ever_in_programme,
                                                                  cat_document)

all_factories_ever_active_panel_balanced <- panel_production_all_factories_ever%>%
  filter(balance == 1 & all_zero == 0)


balanced_and_complete_panel <- panel_production%>%
  filter(balance == 1 & all_zero == 0)

non_zero_panels <- panel_production%>%
  filter(all_zero == 0)


write.csv(balanced_and_complete_panel, "Panel with Downward Trend and Non Zero Filter.csv", row.names = F)
write.csv(non_zero_panels, "Panel (balanced and unbalanced with Non Zero Filter.csv", row.names = F)


write.csv(all_factories_ever_active_panel_balanced,"Panel with Downward Trend all factories ever active Indonesia.csv", row.names =F)
###group bythe unique panel identifier, and then check if it has min cycle  == 1 and max cycle == from panel

"Factories with at least 3 "


```

#CP level
```{r}

generate_cp_level_nc_rates <- function(countries = NULL,cycle_vec,df_of_data,active_factories_df){
  
  
    if(is.null(countries)){
      temp_df <- df_of_data
    }else{
      temp_df <- df_of_data%>%
        filter(Country %in% countries)
    }
    
    temp_df <- temp_df[!grepl("(Obsolete)",temp_df$Factory.Assessed.Name),]

    ###getting the largest question_id for the temp_df for any given global identifier
    ###this is just to use for labeling purposess
    
    
    temp_df <- temp_df[temp_df$Question.type != "FGW",]
  
    temp_df$converted_finding <- as.integer(temp_df$Finding)
    # temp_df$public_reporting <- ifelse(grepl("Public Disclosure",temp_df$Tags),1,0)
  
    
  ####the panel construction portion...
    
  latest_cycle_for_active_factories <- temp_df%>%
    group_by(Factory.Assessed.ID)%>%
    summarise(Cycle = max(Cycle))%>%
    filter(Factory.Assessed.ID %in% active_factories_df$ID)
  
  output_df <- data.frame(Country = character(),
                          CP = character(),
                          Cluster = character(),
                          Cycle =integer(),
                          total_ncs = integer(),
                          total_factories = integer(),
                          nc_rate = numeric())
  
  for(cyc in cycle_vec){
    
    #these are factories that have has at least as many cycles as the cycle passed in the loop
    factories_to_use <- temp_df%>%
      filter(Factory.Assessed.ID %in% latest_cycle_for_active_factories$Factory.Assessed.ID)%>%
      filter(Cycle >= cyc)%>%
      group_by(Factory.Assessed.ID)%>%
      summarise(n=n())
    ####need to merge in the information....
    temp_panel_data <- temp_df%>%
      filter(Factory.Assessed.ID %in% factories_to_use$Factory.Assessed.ID)%>%
      filter(Cycle <= cyc)
    
    panel_df <- temp_panel_data%>%
      group_by(Country,Factory.Assessed.ID,CP,Cluster,Cycle)%>%
      summarise(cp_ncs = sum(converted_finding))%>%
      mutate(is_cp_nc = ifelse(cp_ncs >=1, 1,0))%>%
      group_by(Country,CP,Cluster,Cycle)%>%
      summarise(total_ncs = sum(is_cp_nc),
                total_factories = n_distinct(Factory.Assessed.ID),
                nc_rate = sum(is_cp_nc)/n_distinct(Factory.Assessed.ID))
    
    output_df <- rbind(output_df,panel_df)
    
  }
  
  ####could also modify to calculate which CP trends are downward....
  ####but its just setting up and click through 8 clusters and making visual
  #### notice so it may not be an issue
  
  return(output_df)
  
}

panel_cp_level <- generate_cp_level_nc_rates(countries,
                           cycle_vector,
                           all_bw_assessments_through_8_feb_2022,
                           active_factories_used_for_end_of_year_reporting)
  
complete_panels <- panel_cp_level%>%
  group_by(Country,Cycle)%>%
  summarise(total_factories = max(total_factories))%>%
  filter(Cycle >= 3)%>%
  mutate(complete_dummy = 1)%>%
  select(Country, total_factories,complete_dummy,Cycle)%>%
  filter(total_factories >= 10)%>%
  mutate(panel_labels = paste0(total_factories, " Factories "," Across ",Cycle," Cycles"))%>%
  select(Country, total_factories,panel_labels)

panel_cp_level_with_labels <- inner_join(panel_cp_level,complete_panels,
                             by = c("Country","total_factories"))%>%
  distinct()

downward_trend <- panel_cp_level_with_labels%>%
  group_by(panel_labels,CP)%>%
  summarise(max_cycle = max(Cycle),
            min_cycle = min(Cycle))


```


## Outputs
```{r}
#Question and Compliance Point level Outputs"

write.csv(non_zero_panels,
          file = question_level_panel_string_file_names, na = "", row.names = F)

write.csv(panel_cp_level_with_labels,file = compliance_point_level_panel_string_file_names,na = '',row.names = F)


# Indonesia Question Level Panel for factories with at least 3 - 10 Cycles with Better Work.csv
# " Indonesia Compliance Point Level Panel for factories with at least 3 - 10 Cycles with Better Work.csv"

# are inputs to be used for

# the file

# Indonesia Question Panel with Downward Trend and Non Zero Filter.xlsx

ggplot(balanced_and_complete_panel,aes(x=nc_rate))+
  geom_density(aes(color=Country))+
  facet_wrap(~Cluster)

test <- balanced_and_complete_panel%>%
  group_by(Country,Cluster)%>%
  summarise(skew=moments::skewness(nc_rate))


train <- data.frame("text"=unique(cat_document$text[str_detect(cat_document$text,"train")]),"Q-type"="Training")
union <- data.frame("text"=unique(cat_document$text[str_detect(cat_document$text,"union | collective bargaining")]),"Q-type"="Training")

PICC <- data.frame("text"=unique(cat_document$text[str_detect(cat_document$text,"PICC")]),"Q-type"="PICC")

man_sys <- data.frame("text"=unique(cat_document$text[str_detect(cat_document$text,"management system")]),"Q-type"="Management Systems")

gender <- data.frame("text"=unique(cat_document$text[str_detect(cat_document$text,"gender|female")]),"Q-type"="Gender")

WP <- data.frame("text"=unique(cat_document$text[str_detect(cat_document$text,"workplace | noise")]),"Q-type"="Workplace")

wage <-  data.frame("text"=unique(cat_document$text[str_detect(cat_document$text,"minimum wage")]),"Q-type"="Minimum Wage")

temp <- bind_rows(train, union,PICC,man_sys,gender,WP,wage)

write.xlsx(temp,file="/Users/malik/Dropbox (GALILEO)/Master Thesis/RManual-master/cycle-trend-panel-creation-main/Driver_Questions.xlsx")

```
